In [2]:
import numpy as np
a=np.array([7,9,9,2])
print(a)

[7 9 9 2]


In [3]:
b=np.array([(7,9,9,2),(16,11,9,6)])
print(b)

[[ 7  9  9  2]
 [16 11  9  6]]


In [7]:
c=np.arange(10)
print(c)
d=np.linspace(1,5,9)
print(d)

[0 1 2 3 4 5 6 7 8 9]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [11]:
a=np.array([7,9,9,2])
b=np.array([(7,9,9,2),(16,11,9,6)])
print(b.ndim)
print(a.itemsize)
print(a.dtype)
print(b.size*b.itemsize)
print(a.size)
print(b.shape)

2
8
int64
64
4
(2, 4)


In [13]:
b=np.array([(7,9,9,2),(16,11,9,6)])
print(b)
b=b.reshape(4,2)
print(b)

[[ 7  9  9  2]
 [16 11  9  6]]
[[ 7  9]
 [ 9  2]
 [16 11]
 [ 9  6]]


In [15]:
b=np.array([(7,9,9,2),(16,11,9,6)])
print(b[0,2])
print(b[0:,2])

9
[9 9]


In [18]:
e=np.array([7,9,9,2,16,11,96])
print(e.min())
print(e.max())
print(e.sum())

2
96
150


In [21]:
a=np.array([7,9,9,2])
b=np.array([1,9,9,6])
print(a+b)
print(a*b)
print(a-b)
print(a/b)

[ 8 18 18  8]
[ 7 81 81 12]
[ 6  0  0 -4]
[7.         1.         1.         0.33333333]


In [29]:
a=np.array([7,9,9,2])
b=np.array([(7,9,9,2),(16,11,9,6)])
print(b.sum(axis=0))
print(b.sum(axis=1))
print(np.sqrt(a))
print(np.sqrt(b))
print(np.std(a))
print(np.exp(a))
print(np.log(a))
print(np.log10(a))

[23 20 18  8]
[27 42]
[2.64575131 3.         3.         1.41421356]
[[2.64575131 3.         3.         1.41421356]
 [4.         3.31662479 3.         2.44948974]]
2.8613807855648994
[1.09663316e+03 8.10308393e+03 8.10308393e+03 7.38905610e+00]
[1.94591015 2.19722458 2.19722458 0.69314718]
[0.84509804 0.95424251 0.95424251 0.30103   ]


In [45]:
import numpy as np
b=np.array([[7,9,9,2],[16,11,9,6]])
f=np.array([[1,2,3,4],[5,6,7,8]])
print(np.vstack((b,f)))
print(np.hstack((b,f)))
print(b.ravel())

[[ 7  9  9  2]
 [16 11  9  6]
 [ 1  2  3  4]
 [ 5  6  7  8]]
[[ 7  9  9  2  1  2  3  4]
 [16 11  9  6  5  6  7  8]]
[ 7  9  9  2 16 11  9  6]
